language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - export CITS_VERSION=1.0-SNAPSHOT
  - export CITS_TAG=v1.0-snapshot
  - export CITS_REPO=CognizantQAHub/Cognizant-Intelligent-Test-Scripter
  - curl -O -L "https://github.com/$CITS_REPO/releases/download/$CITS_TAG/cognizant-intelligent-test-scripter-$CITS_VERSION-setup.zip"
  - unzip "cognizant-intelligent-test-scripter-$CITS_VERSION-setup.zip"
  - cd "cognizant-intelligent-test-scripter-$CITS_VERSION"
  - chmod u+x Run.command
  - ./Run.command -version
  
  
script: "./Run.command -run -project_location Projects/DemoProject -scenario BasicFeatures -testcase DemoTestCase -browser PhantomJS"
